Repository AY2425S2-CS2113-T11a-3/tp, pull requests merged in 2025-04, with the labels that each got.

#129 Update DG for EditCommand and UI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/edit_full_seq_diag.png
  docs/images/edit_overview.png
  docs/images/edit_ref_1.png
  docs/images/edit_ref_2.png
  docs/images/projects-uml.png
  docs/images/ui-class-diagram.png
  docs/images/ui_sequence_diagrams.png
Labels: priority.Medium

#131 Add save functionality with Storage interface
  data/internships.txt
  data/user.txt
  log/InternSprint.log
  src/main/java/seedu/internsprint/logic/command/internship/HelpCommand.java
  src/main/java/seedu/internsprint/logic/command/user/ViewGeneralProjectsCommand.java
  src/main/java/seedu/internsprint/logic/command/user/ViewHardwareProjectsCommand.java
  src/main/java/seedu/internsprint/logic/command/user/ViewSoftwareProjectsCommand.java
  src/main/java/seedu/internsprint/logic/command/user/ViewUserCommand.java
  src/main/java/seedu/internsprint/model/internship/interview/Interview.java
  src/main/java/seedu/internsprint/model/internship/interview/InterviewList.java
  src/main/java/seedu/internsprint/model/userprofile/UserProfile.java
  src/main/java/seedu/internsprint/model/userprofile/project/ProjectList.java
  src/main/java/seedu/internsprint/storage/InterviewStorageHandler.java
  src/main/java/seedu/internsprint/storage/ProfileStorageHandler.java
  src/main/java/seedu/internsprint/storage/ProjectStorageHandler.java
  src/main/java/seedu/internsprint/storage/StorageManager.java
  src/main/java/seedu/internsprint/util/InternSprintExceptionMessages.java
  src/main/java/seedu/internsprint/util/InternSprintMessages.java
Labels: priority.High, severity.High

#135 Branch dg
  docs/DeveloperGuide.md
  docs/images/ListImages/list_full_seq_diag.png
  docs/images/ListImages/list_overview.png
  docs/images/ListImages/list_ref_1.png
  docs/images/ListImages/list_ref_2.png
  docs/images/Model_UML_diag.png
Labels: priority.High

#226 Refactoring of sortInterviews and interviewsFor commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/internsprint/logic/command/internship/AddInterviewCommand.java
  src/main/java/seedu/internsprint/logic/command/internship/HelpCommand.java
  src/main/java/seedu/internsprint/logic/command/internship/SortInterviewCommand.java
  src/main/java/seedu/internsprint/logic/parser/CommandParser.java
  src/main/java/seedu/internsprint/util/InternSprintExceptionMessages.java
Labels: priority.Medium

#255 Update Nikita ppp
  docs/team/nmarwah7.md
Labels: priority.High

#261 Refactor Junit tests to add BeforeEach test set-up
  src/test/java/seedu/internsprint/logic/command/internship/ListCommandTest.java
  src/test/java/seedu/internsprint/logic/command/internship/SortInterviewCommandTest.java
Labels: priority.Medium

#268 Adjust column width for "notes" column
  src/main/java/seedu/internsprint/logic/command/internship/SortInterviewCommand.java
Labels: priority.Low

#281 Branch update ppp
  docs/team/prathisttam.md
Labels: priority.High
