Repository AY2425S2-CS2113-T11a-3/tp, pull requests merged in 2025-03, with the labels that each got.

#49 Refactor edit and delete
  src/main/java/seedu/internsprint/InternSprint.java
  src/main/java/seedu/internsprint/command/DeleteCommand.java
  src/main/java/seedu/internsprint/command/EditCommand.java
  src/main/java/seedu/internsprint/command/HelpCommand.java
  src/main/java/seedu/internsprint/handler/Parser.java
  src/main/java/seedu/internsprint/internship/InternshipList.java
  src/main/java/seedu/internsprint/util/InternSprintExceptionMessages.java
  src/test/java/seedu/internsprint/command/DeleteCommandTest.java
  src/test/java/seedu/internsprint/command/EditCommandTest.java
Labels: type.Bug, severity.High

#45 UI updates and corrections
  src/main/java/seedu/internsprint/command/AddCommand.java
  src/main/java/seedu/internsprint/command/DeleteCommand.java
  src/main/java/seedu/internsprint/command/DescriptionCommand.java
  src/main/java/seedu/internsprint/command/EditCommand.java
  src/main/java/seedu/internsprint/command/HelpCommand.java
  src/main/java/seedu/internsprint/command/ListCommand.java
  src/main/java/seedu/internsprint/handler/StorageHandler.java
  src/main/java/seedu/internsprint/util/InternSprintMessages.java
  src/main/java/seedu/internsprint/util/Ui.java
  src/test/java/seedu/internsprint/command/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#66 Update user guide
  docs/README.md
  docs/UserGuide.md
Labels: type.Task, priority.Low

#83 Add project package
  src/main/java/seedu/internsprint/project/GeneralProject.java
  src/main/java/seedu/internsprint/project/HardwareProject.java
  src/main/java/seedu/internsprint/project/Project.java
  src/main/java/seedu/internsprint/project/ProjectList.java
  src/main/java/seedu/internsprint/project/SoftwareProject.java
Labels: priority.Medium, type.Task

#46 Create user profile class
  data/internships.txt
  log/InternSprint.log
  src/main/java/seedu/internsprint/InternSprint.java
  src/main/java/seedu/internsprint/command/AddInternshipCommand.java
  src/main/java/seedu/internsprint/command/AddInterviewCommand.java
  src/main/java/seedu/internsprint/command/AddSoftwareInternshipCommand.java
  src/main/java/seedu/internsprint/command/ByeCommand.java
  src/main/java/seedu/internsprint/command/Command.java
  src/main/java/seedu/internsprint/command/DeleteCommand.java
  src/main/java/seedu/internsprint/command/DescriptionCommand.java
  src/main/java/seedu/internsprint/command/EditCommand.java
  src/main/java/seedu/internsprint/command/FindCommand.java
  src/main/java/seedu/internsprint/command/HelpCommand.java
  src/main/java/seedu/internsprint/command/ListCommand.java
  src/main/java/seedu/internsprint/command/UserProfileCommand.java
  src/main/java/seedu/internsprint/command/ViewUserCommand.java
  src/main/java/seedu/internsprint/handler/CommandParser.java
  src/main/java/seedu/internsprint/interview/Interview.java
  src/main/java/seedu/internsprint/userprofile/UserProfile.java
  src/main/java/seedu/internsprint/util/InternSprintExceptionMessages.java
  src/main/java/seedu/internsprint/util/InternSprintMessages.java
  src/test/java/seedu/internsprint/command/AddInternshipCommandTest.java
  src/test/java/seedu/internsprint/command/DeleteCommandTest.java
  src/test/java/seedu/internsprint/command/DescriptionCommandTest.java
  src/test/java/seedu/internsprint/command/EditCommandTest.java
  src/test/java/seedu/internsprint/command/FindCommandTest.java
  src/test/java/seedu/internsprint/command/HelpCommandTest.java
  src/test/java/seedu/internsprint/command/ListCommandTest.java
  src/test/java/seedu/internsprint/command/UserProfileCommandTest.java
  src/test/java/seedu/internsprint/command/ViewUserCommandTest.java
Labels: priority.Medium, type.Task

#97 Add in DG Sequence Diagram and content for Edit Command
  docs/DeveloperGuide.md
  docs/images/Edit_command.drawio.png
Labels: priority.Low

#100 Add to developers guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#104 Add sortInterviews class
  src/main/java/seedu/internsprint/command/SortInterviewCommand.java
  src/main/java/seedu/internsprint/handler/CommandParser.java
  src/main/java/seedu/internsprint/internship/Internship.java
  src/main/java/seedu/internsprint/interview/Interview.java
  src/main/java/seedu/internsprint/interview/InterviewEntry.java
Labels: priority.High

#108 Add JUnit tests to List class
  src/main/java/seedu/internsprint/command/AddHardwareInternshipCommand.java
  src/test/java/seedu/internsprint/command/ListCommandTest.java
Labels: priority.Medium

#107 Add full JUnit test coverage for Interview class
  src/main/java/seedu/internsprint/interview/Interview.java
  src/test/java/seedu/internsprint/interview/InterviewTest.java
Labels: priority.High

#101 Add command for projects
  src/main/java/seedu/internsprint/command/ProjectCommand.java
  src/main/java/seedu/internsprint/command/ProjectGeneralCommand.java
  src/main/java/seedu/internsprint/command/ProjectHardwareCommand.java
  src/main/java/seedu/internsprint/command/ProjectSoftwareCommand.java
  src/main/java/seedu/internsprint/command/ViewGeneralProjectsCommand.java
  src/main/java/seedu/internsprint/command/ViewHardwareProjectsCommand.java
  src/main/java/seedu/internsprint/command/ViewSoftwareProjectsCommand.java
  src/main/java/seedu/internsprint/handler/CommandParser.java
  src/main/java/seedu/internsprint/project/GeneralProject.java
  src/main/java/seedu/internsprint/project/HardwareProject.java
  src/main/java/seedu/internsprint/project/Project.java
  src/main/java/seedu/internsprint/project/SoftwareProject.java
  src/main/java/seedu/internsprint/util/InternSprintMessages.java
Labels: priority.High

#115 Update User Guide for list, description and sortInterviews commands
  docs/UserGuide.md
Labels: priority.High
